services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"   # MQTT Port
      - "9001:9001"   # WebSockets (falls aktiviert)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./sensor.sh:/sensor.sh

  publisher:
    build:
      context: ./MavenDemo
    container_name: mqtt-publisher
    depends_on:
      - mosquitto
    restart: unless-stopped
