scrape_configs:
  - job_name: 'nodes'
    static_configs:
    scrape_interval: 10s
      - targets:
       - ['demo1:9100', 'demo2:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
       - cadvisor:8080
